name: Django Action
description: Automatically runs some django tasks.

author: Conrad Großer <conrad@noah.tech>

inputs:
  commit_options:
    description: Commit options for the changed data
    required: false
  commit_message:
    description: Commit message of the changed data
    required: false
    default: "Added data schema"
  pip_path:
    description: Path relative to the repository root, where the requirements.txt is located
    required: false
    default: "requirements.txt"
  output_path:
    description: Output path for the generated data scheme
    required: false
    default: "schema.png"
  project_path:
    description: Path to the folder where manage.py is located
    required: false
    default: "./"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book"
  color: "green"
